apiVersion: v1
kind: Service
metadata:
  name: simple-web
  labels:
    app: simple-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: customer
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "simple-web"
  namespace: "default"
  labels:
    app: "simple-web"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "simple-web"
  template:
    metadata:
      labels:
        app: "simple-web"
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: "customer-simple-web-key"
      containers:
      - name: simple-web
        image: us.gcr.io/gitdocker/simple-web:latest
        command: ["./main"]
        args: [@args@]
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "customer-hpa-simple-web"
  namespace: "default"
  labels:
    app: "customer"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "customer-simple-web"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
