apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-web
  labels:
    app: simple-web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: web
        image: us.gcr.io/gitdocker/simple-web:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
kind: Service
apiVersion: v1
metadata:
  name: web2-service
spec:
  selector:
    app: MyApp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
