apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: simple-web
spec:
  replicas: 2
  containers:
  - name: nginx
    image: us.gcr.io/gitdocker/simple-web:latest
    ports:
    - containerPort: 80
kind: Pod
metadata:
  name: web-pod
  labels:
    app: simple-web
spec:
  containers:
  - name: myapp-container
    image: us.gcr.io/gitdocker/simple-web:latest
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
kind: Service
apiVersion: v1
metadata:
  name: web2-service
spec:
  selector:
    app: MyApp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
